# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.05.01

minecraft_release=1.21.1
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neoforge_version=21.1.194
neoforge_version_range=[21.1.194,)
loader_version_range=[1,)

mod_id=functionalchemical
mod_name=Functional Chemical
mod_jar_name=FunctionalChemical
mod_license=LGPL-3.0
mod_version=1.21.1-1.0
mod_group_id=com.glodblock.github.functionalchemical
mod_authors=GlodBlock
mod_description=Mekanism chemical support for Functional Storage
